language: node_js

node_js:
  - 'stable'

sudo: false

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: "Gq+mx8u+CMAEzIP0C29TT3iCqhY2lsNFFiyJZYOqeMnhG1QK4lfK+9KBq9sh6xGJV+AyR7X8Ir6uiSOvKdWQCEPJO1/j+52sYZzsVhgmL5pNRxV9keUr0v/OhQQJYloOFdNr9FqqOA4zTS7+dVoIrdBy0K+/sIsEhjdfOuxpQfQ8e3fRd9E34lvUEE+qZq0d2aGfE+ECdpofe68XPFk6QMhxi1p/rW+biSdnrY69cz+pNsyNWYfBog9/pacPt9YiQkI4xVFbe8jUinUMAvzDNF7sUCmrjCqCR7rYliE6LMGgFZ/gCBJCcD2xceXAXq0+adUUyh7g7gIckyslZ0uyqzP6hDbX4aE6ooHIKV9IfpzvTSdgZSKloel4XVK4gPeHFBd4ngbwd5/pAZ01NOc6x/ZT3zQKPMjMz6DK63iASX9eJrhB6vhKPf70YQ83gddMZWx2zn3nb9pfLA98Gcrlnob2rY+LM1FEeh8xS/2fMVTfpmFN+dCWTD7p8uAL30Reop0T/GgEPpTnYtH55oykYXaYRKbk3Q9GspZyWO9zpUyu6odZ/sH3RWAEab6cGrNKRHvUsaIyKuyDQ29V0TxNgrSgxK3EcFLtUUCjCSJdeA2AX7Lw05A/Ip/WMKk5kZRl1aEBLw1loqucyGsFuIT7x+h+SzgPpNI7SFe7owkG1nQ="
    on:
      tags: true
      node: 'stable'
